name: Proxy Scanner
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        
      - name: Start Scan
        run: |
          bun install && bun run ./proxyip.ts
          
      - name: Publish Result
        if: ${{ success() }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update proxyip - $(date +'%Y-%m-%d %H:%M:%S')" --allow-empty
          git push origin main --force
          
      - name: Cleanup Old Workflow Runs
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          gh run list -L 100 --json databaseId -q '.[].databaseId' | \
          grep -v "${{ github.run_id }}" | \
          xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :
